services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    # Uncomment the following line if you are using WSL2 and experiencing issues with file watching
    # environment:
    #   - WATCHPACK_POLLING=true
    restart: unless-stopped
